#
# TODO: Add a proper CMakeLists.txt file and install the ruby files
#

ui_engineexplorer.rb: engineexplorer.ui
	rbuic4 -tr KDE::tr2i18n engineexplorer.ui -o ui_engineexplorer.rb

clean:
	rm ui_engineexplorer.rb

